spring.application.name=Usable
spring.datasource.url=jdbc:postgresql://localhost:5432/Usabledb
spring.datasource.username=postgres
spring.datasource.password=Neet2006@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
